# III. Creating a model to fit the 4 Scalar coupling data features

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df_train = pd.read_pickle(f'../input/molecular-properties-data-create/df_train_new.pkl')

/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [3]:
df_scalar = pd.read_csv(f'../input/champs-scalar-coupling/scalar_coupling_contributions.csv')

Fitting on the data, we merge the data with the required scalar_coupling data

In [4]:
df_train = df_train.sample(frac = 0.5)
df_train.head()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,...,g4_1_0.2_0.5_1_1,g4_1_0.2_0.5_8_1,g4_1_0.2_0.5_16_1,g2_1.5_0.2_1,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1
4227200,4227196,dsgdb9nsd_118275,10,11,2JHH,-9.734375,0.676758,0.672852,0.157715,0.078003,...,0.109009,0.009178,0.000545,0.657715,0.147949,0.073181,0.033020,0.114868,0.009651,0.000573
2336891,2336899,dsgdb9nsd_071783,9,0,1JHC,81.937500,0.680664,0.676270,0.162476,0.080139,...,0.000000,0.000000,0.000000,0.491699,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1056311,1056326,dsgdb9nsd_036473,14,3,3JHN,4.093750,0.591797,0.586914,0.076904,0.039703,...,0.004620,0.000394,0.000026,0.756348,0.007195,0.003815,0.002096,0.005661,0.000478,0.000032
1662128,1662137,dsgdb9nsd_053914,11,3,1JHC,97.750000,0.508789,0.504883,0.004009,0.001522,...,0.000000,0.000000,0.000000,0.414307,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1001659,1001637,dsgdb9nsd_034977,12,6,3JHC,7.503906,0.593750,0.588867,0.080688,0.040527,...,0.032257,0.000123,0.000002,1.411133,0.027893,0.000442,0.000103,0.034210,0.000144,0.000003

In [5]:
df_train = df_train.merge(df_scalar, on = ['molecule_name', 'atom_index_0', 'atom_index_1'])

In [6]:
df_train.drop(columns= ['id', 'molecule_name','atom_index_0', 'atom_index_1', 'type_y', 'scalar_coupling_constant'], inplace=True)

In [7]:
df_train.head()

,type_x,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,g4_2_0.01_1_16_0,g4_2_0.01_-1_1_0,g4_2_0.01_-1_8_0,g4_2_0.01_-1_16_0,g2_6_0.01_0,...,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1,fc,sd,pso,dso
0,2JHH,0.676758,0.672852,0.157715,0.078003,0.035217,0.016891,5.960464e-08,0.0,0.541504,...,0.147949,0.073181,0.033020,0.114868,0.009651,0.000573,-9.72879,0.421269,2.089580,-2.519130
1,1JHC,0.680664,0.676270,0.162476,0.080139,0.036011,0.017502,5.960464e-08,0.0,0.543945,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,80.13740,0.148117,0.947435,0.724345
2,3JHN,0.591797,0.586914,0.076904,0.039703,0.018661,0.007614,0.000000e+00,0.0,0.468994,...,0.007195,0.003815,0.002096,0.005661,0.000478,0.000032,4.14334,-0.023181,0.104813,-0.130312
3,1JHC,0.508789,0.504883,0.004009,0.001522,0.000507,0.000598,0.000000e+00,0.0,0.401123,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,96.50550,0.027348,-0.127054,1.338660
4,3JHC,0.593750,0.588867,0.080688,0.040527,0.018433,0.008347,0.000000e+00,0.0,0.471191,...,0.027893,0.000442,0.000103,0.034210,0.000144,0.000003,7.62802,-0.001876,0.325138,-0.445913

Now that all the columns that aren't required for prediction are removed, we can fit the above cleaned features on the 4 factors, namely:
- fc
- sd
- pso
- dso

In [8]:
target_y = ['fc', 'sd', 'pso', 'dso']

y_train = df_train[target_y]

X_train = df_train.drop(columns = target_y)

In [9]:
X_train.shape

(2329072, 213)

In [10]:
X_train.head()

,type_x,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,g4_2_0.01_1_16_0,g4_2_0.01_-1_1_0,g4_2_0.01_-1_8_0,g4_2_0.01_-1_16_0,g2_6_0.01_0,...,g4_1_0.2_0.5_1_1,g4_1_0.2_0.5_8_1,g4_1_0.2_0.5_16_1,g2_1.5_0.2_1,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1
0,2JHH,0.676758,0.672852,0.157715,0.078003,0.035217,0.016891,5.960464e-08,0.0,0.541504,...,0.109009,0.009178,0.000545,0.657715,0.147949,0.073181,0.033020,0.114868,0.009651,0.000573
1,1JHC,0.680664,0.676270,0.162476,0.080139,0.036011,0.017502,5.960464e-08,0.0,0.543945,...,0.000000,0.000000,0.000000,0.491699,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,3JHN,0.591797,0.586914,0.076904,0.039703,0.018661,0.007614,0.000000e+00,0.0,0.468994,...,0.004620,0.000394,0.000026,0.756348,0.007195,0.003815,0.002096,0.005661,0.000478,0.000032
3,1JHC,0.508789,0.504883,0.004009,0.001522,0.000507,0.000598,0.000000e+00,0.0,0.401123,...,0.000000,0.000000,0.000000,0.414307,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,3JHC,0.593750,0.588867,0.080688,0.040527,0.018433,0.008347,0.000000e+00,0.0,0.471191,...,0.032257,0.000123,0.000002,1.411133,0.027893,0.000442,0.000103,0.034210,0.000144,0.000003

Encoding the multi-class labels of the molecule type

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(X_train['type_x'])
le.classes_

array(['1JHC', '1JHN', '2JHC', '2JHH', '2JHN', '3JHC', '3JHH', '3JHN'],
      dtype=object)

In [12]:
X_train['type_x'] = le.transform(X_train['type_x'])

In [13]:
X_train.head()

,type_x,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,g4_2_0.01_1_16_0,g4_2_0.01_-1_1_0,g4_2_0.01_-1_8_0,g4_2_0.01_-1_16_0,g2_6_0.01_0,...,g4_1_0.2_0.5_1_1,g4_1_0.2_0.5_8_1,g4_1_0.2_0.5_16_1,g2_1.5_0.2_1,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1
0,3,0.676758,0.672852,0.157715,0.078003,0.035217,0.016891,5.960464e-08,0.0,0.541504,...,0.109009,0.009178,0.000545,0.657715,0.147949,0.073181,0.033020,0.114868,0.009651,0.000573
1,0,0.680664,0.676270,0.162476,0.080139,0.036011,0.017502,5.960464e-08,0.0,0.543945,...,0.000000,0.000000,0.000000,0.491699,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,7,0.591797,0.586914,0.076904,0.039703,0.018661,0.007614,0.000000e+00,0.0,0.468994,...,0.004620,0.000394,0.000026,0.756348,0.007195,0.003815,0.002096,0.005661,0.000478,0.000032
3,0,0.508789,0.504883,0.004009,0.001522,0.000507,0.000598,0.000000e+00,0.0,0.401123,...,0.000000,0.000000,0.000000,0.414307,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,0.593750,0.588867,0.080688,0.040527,0.018433,0.008347,0.000000e+00,0.0,0.471191,...,0.032257,0.000123,0.000002,1.411133,0.027893,0.000442,0.000103,0.034210,0.000144,0.000003

## Data normalization

Since there are 4 fields of y, predicting them without normalization results in less accurate solutions (based on the last hidden layer) or would require separate model for each.
To circumvent this issue, we'll normalize the Outputs and restore the values after the predictions are made.

In [14]:
y_mean = y_train.mean()
y_min = y_train.min()
y_max = y_train.max()
# y_min

'''
Note: To ensure all values lie within the (-1,1) range we make the following computation
'''
y_train = (y_train - y_mean) / (1.2 * (y_max - y_min))
y_train.head()

         fc        sd       pso       dso
0 -0.087383  0.055173  0.166983 -0.243831
1  0.221308  0.010689  0.055715  0.102220
2 -0.039732 -0.017207 -0.026373  0.011036
3  0.277533 -0.008978 -0.048962  0.167762
4 -0.027762 -0.013737 -0.004909 -0.022636

In [15]:
X_train.head()

,type_x,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,g4_2_0.01_1_16_0,g4_2_0.01_-1_1_0,g4_2_0.01_-1_8_0,g4_2_0.01_-1_16_0,g2_6_0.01_0,...,g4_1_0.2_0.5_1_1,g4_1_0.2_0.5_8_1,g4_1_0.2_0.5_16_1,g2_1.5_0.2_1,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1
0,3,0.676758,0.672852,0.157715,0.078003,0.035217,0.016891,5.960464e-08,0.0,0.541504,...,0.109009,0.009178,0.000545,0.657715,0.147949,0.073181,0.033020,0.114868,0.009651,0.000573
1,0,0.680664,0.676270,0.162476,0.080139,0.036011,0.017502,5.960464e-08,0.0,0.543945,...,0.000000,0.000000,0.000000,0.491699,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,7,0.591797,0.586914,0.076904,0.039703,0.018661,0.007614,0.000000e+00,0.0,0.468994,...,0.004620,0.000394,0.000026,0.756348,0.007195,0.003815,0.002096,0.005661,0.000478,0.000032
3,0,0.508789,0.504883,0.004009,0.001522,0.000507,0.000598,0.000000e+00,0.0,0.401123,...,0.000000,0.000000,0.000000,0.414307,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,0.593750,0.588867,0.080688,0.040527,0.018433,0.008347,0.000000e+00,0.0,0.471191,...,0.032257,0.000123,0.000002,1.411133,0.027893,0.000442,0.000103,0.034210,0.000144,0.000003

## Modeling using a Neural network

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import cross_val_score

Using TensorFlow backend.

In [17]:
N, m = X_train.shape

In [18]:
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from keras.models import load_model

In [19]:
# from sklearn.datasets import make_moons
from keras.models import Sequential
from keras.layers import Dense, BatchNormalization, LeakyReLU
from keras.layers import Dropout
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from matplotlib import pyplot
from keras.models import load_model
# generate 2d classification dataset
    
def train_model(X_train, y_train, n_epochs, model):
    # simple early stopping
    es = EarlyStopping(monitor='val_loss', verbose=1, patience=200)  # , mode='min'
    mc = ModelCheckpoint('best_model.h5', monitor='val_loss', verbose=0, save_best_only=True)  # , mode='min'
    # fit model
    history = model.fit(X_train, y_train, validation_split=0.2, epochs=n_epochs, verbose=0, callbacks=[es, mc])
    # load the saved model
    saved_model = load_model('best_model.h5')
    return saved_model
# evaluate the model
# saved_model = train_model(X_train[20_000:30_000], y_train[20_000:30_000], 1, None)
# _, train_acc = saved_model.evaluate(trainX, trainy, verbose=0)
# _, test_acc = saved_model.evaluate(testX, testy, verbose=0)
# print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))

In [20]:
index_lst = []

div = 5
diff = N//div

for j in range(div):
    index_lst.append((j)* diff)
    
index_lst.append(N) 
index_lst = np.array(index_lst)

In [21]:
def iterative_train(X_train, y_train, indices, n_epochs= 10):
    model = model_()
    
    for i in range(len(indices)-1):  # 1
        print(indices[i+1])
        saved_model = train_model(X_train[indices[i]:indices[i+1]], y_train[indices[i]:indices[i+1]], n_epochs, model)
        model = saved_model
    return model

In [22]:
# define model
def model_():
    model = Sequential()
    model.add(Dense(50, input_dim=m))
    model.add(Dropout(0.3))

    model.add(Dense(100))
    model.add(BatchNormalization())
    model.add(LeakyReLU(0.1))

    model.add(Dense(30))
    model.add(BatchNormalization())
    model.add(LeakyReLU(0.1))

    model.add(Dense(30))
    model.add(BatchNormalization())
    model.add(LeakyReLU(0.1))
    
    model.add(Dense(30))
    model.add(BatchNormalization())
    model.add(LeakyReLU(0.1))
   
    model.add(Dense(30))
    model.add(BatchNormalization())
    model.add(LeakyReLU(0.1))
    
    model.add(Dense(4, activation='tanh'))
    model.compile(loss='mae', optimizer='adam')
    return model

In [23]:
model = iterative_train(X_train, y_train, index_lst) # index_lst

465814
931628
1397442
1863256
2329072

In [24]:
del X_train
del y_train
del df_train
del df_scalar

In [25]:
import gc

In [26]:
gc.collect()

132

In [29]:
arr_y_mean = np.array([y_mean])
arr_y_min = np.array(y_min)
arr_y_max = np.array(y_max)

arr_y_min.shape

(4,)

In [30]:
df_test = pd.read_pickle(f'../input/molecular-properties-data-create/df_test_new.pkl')

In [31]:
df_test.drop(columns= ['id', 'molecule_name','atom_index_0', 'atom_index_1'], inplace=True)
df_test.head()

,type,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,g4_2_0.01_1_16_0,g4_2_0.01_-1_1_0,g4_2_0.01_-1_8_0,g4_2_0.01_-1_16_0,g2_6_0.01_0,...,g4_1_0.2_0.5_1_1,g4_1_0.2_0.5_8_1,g4_1_0.2_0.5_16_1,g2_1.5_0.2_1,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1
0,2JHC,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
1,1JHC,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
2,1JHC,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
3,2JHC,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
4,3JHH,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.506836,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
df_test['type'] = le.transform(df_test['type']) 
df_test.head()

,type,g1_0,g2_2_0.01_0,g4_2_0.01_1_1_0,g4_2_0.01_1_8_0,g4_2_0.01_1_16_0,g4_2_0.01_-1_1_0,g4_2_0.01_-1_8_0,g4_2_0.01_-1_16_0,g2_6_0.01_0,...,g4_1_0.2_0.5_1_1,g4_1_0.2_0.5_8_1,g4_1_0.2_0.5_16_1,g2_1.5_0.2_1,g4_1.5_0.2_1_1_1,g4_1.5_0.2_1_8_1,g4_1.5_0.2_1_16_1,g4_1.5_0.2_0.5_1_1,g4_1.5_0.2_0.5_8_1,g4_1.5_0.2_0.5_16_1
0,2,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
1,0,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
2,0,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
3,2,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.928711,0.0,0.0,0.0,0.0,0.0,0.0
4,6,0.526855,0.522461,0.0,0.0,0.0,0.0,0.0,0.0,0.412842,...,0.0,0.0,0.0,0.506836,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
y_pred_test = model.predict(df_test)          # 5 layers
y_pred_test

array([[-0.034085  ,  0.03737868,  0.14640939, -0.05395798],
       [ 0.53693014,  0.1175462 , -0.11032715,  0.04759917],
       [ 0.53693014,  0.1175462 , -0.11032715,  0.04759917],
       ...,
       [-0.04559261, -0.00220188,  0.0114375 , -0.03074809],
       [-0.04550503, -0.00231533,  0.01103688, -0.02976333],
       [-0.04487647, -0.00441853,  0.00490069, -0.01623655]],
      dtype=float32)

In [34]:
test_predic = y_pred_test * (1.2 * (arr_y_max - arr_y_min)) + arr_y_mean 
test_predic

array([[ 5.78739043e+00,  3.12002998e-01,  1.87839536e+00,
        -7.39487283e-01],
       [ 1.72021181e+02,  8.04273239e-01, -7.56960027e-01,
         2.12390420e-01],
       [ 1.72021181e+02,  8.04273239e-01, -7.56960027e-01,
         2.12390420e-01],
       ...,
       [ 2.43729618e+00,  6.89577697e-02,  4.92932681e-01,
        -5.21944956e-01],
       [ 2.46279291e+00,  6.82611149e-02,  4.88820353e-01,
        -5.12714935e-01],
       [ 2.64577937e+00,  5.53463621e-02,  4.25833436e-01,
        -3.85930782e-01]])

In [35]:
df_scalar_test = pd.DataFrame(test_predic, columns=target_y)

In [36]:
df_scalar_test.to_pickle('df_scalar_test.pkl')